name: Run nix_maintained-by

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 5 0 * * *
jobs:
  run_action:
    runs-on: ubuntu-latest
    name: Run 'Nix-Maintained_by'
    steps:
      - uses: actions/checkout@v5 # Clone your code
      - uses: actions/checkout@v5 # Clone NixPkgs
        with:
          path: './nixpkgs'
          repository: 'NixOS/nixpkgs'
      
      - name: Run nix-maintainers-get-packages # Run action 
        uses: qjoly/Nix-Maintained_by@main
        with:
          file: './README.md'
          path_nixpkgs: './nixpkgs/pkgs'
          maintainer: 'qjoly'
