name: Progress Year

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */2 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3.5.1
      with:
        node-version: '15.x'

    - name: Update README.md
      run: |
           node index.js >> README.md

    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
